// Generated by Forge — instruments JSX with data-forge-* attributes.
// Presence of this file makes Next.js compile with Babel instead of SWC. Babel
// only runs under webpack, NOT Turbopack — so the dev server must use webpack
// (Next 16 defaults to Turbopack and needs `--webpack`; Next <=15 uses it by default).
module.exports = {
  presets: ["next/babel"],
  plugins: [["/Users/coreykogan/Desktop/projects/fusion/packages/instrument/dist/forge-babel-plugin.cjs", { root: __dirname }]],
};
