export default function Head() {
  return (
    <>
      <title>About - Corey Kogan</title>
      <meta
        name="description"
        content="I'm Corey, a web developer based in Philadelphia, Pennsylvania."
      />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
