export default function Head() {
  return (
    <>
      <title>Projects - Corey Kogan</title>
      <meta
        name="description"
        content="Here is a small collection of projects I've worked on, many having been built from scratch."
      />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
