export default function Head() {
  return (
    <>
      <title>Blog - Corey Kogan</title>
      <meta
        name="description"
        content="A collection of my thoughts, ideas, and experiences throughout life, my career, and more."
      />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
